# https://raw.githubusercontent.com/hoarder-app/hoarder/main/docker/docker-compose.yml
services:
  web:
    image: ghcr.io/hoarder-app/hoarder-web:0.15.0
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      MEILI_ADDR: http://meilisearch:7700
      DATA_DIR: /data
  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - ./redis:/data
  chromium:
    image: gcr.io/zenika-hub/alpine-chrome:latest
    restart: unless-stopped
    command:
      - --no-sandbox
      - --hide-scrollbars
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
  meilisearch:
    image: getmeili/meilisearch:v1.6
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - ./meilisearch:/meili_data
  workers:
    image: ghcr.io/hoarder-app/hoarder-workers:0.15.0
    restart: unless-stopped
    volumes:
      - ./data:/data
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chromium:9222
      DATA_DIR: /data
    depends_on:
      web:
        condition: service_started
#
# .env
# NEXTAUTH_SECRET=$(openssl rand -base64 36)
# MEILI_MASTER_KEY=$(openssl rand -base64 36)
# NEXTAUTH_URL=http://localhost:3000
