services:
  app:
    image: quay.io/hedgedoc/hedgedoc:1.9.3
    environment:
      CMD_DB_URL: postgresql://postgres:${POSTGRES_PASSWORD}@db/postgres
      CMD_DOMAIN: localhost:3000
      CMD_ALLOW_FREEURL: "true"
    volumes:
      - hedgedoc_data:/hedgedoc/public
    ports: ["3000:3000"]
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:14-alpine
    healthcheck:
      test: pg_isready -U postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_v14:/var/lib/postgresql/data
volumes:
  hedgedoc_data:
  postgres_data_v14:
