[package]
edition = "2021"
name = "poppler-rs"
version = "0.1.0"

[dependencies]
cairo-rs = {version = "0.20.1"}
clap = {version = "4.5.16", features = ["derive", "env"]}
image = "0.25.2"
poppler-rs = "0.24.1"
url = "2.5.2"
