services:
  # maildev:
  #   image: maildev/maildev
  #   ports:
  #     - "1080:1080" # Web UI
  #     - "1025:1025"
  #   environment:
  #     MAILDEV_INCOMING_USER: postmaster
  #     MAILDEV_INCOMING_PASS: password
  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025" # Web UI
      - "1025:1025"
    environment:
      MP_SMTP_AUTH_FILE: /etc/mailpit/auth
      MP_SMTP_AUTH_ALLOW_INSECURE: "true"
    volumes:
      - ./etc/mailpit:/etc/mailpit:ro
