# yaml-language-server: $schema=https://raw.githubusercontent.com/kjellberg/mrsk/validate-with-json-schema/lib/mrsk/configuration/schema.yaml
service: kamal-example
image: caddy
servers:
  - ubuntu@gamma.fogtype.com
registry:
  server: localhost:5000
  username: _
  password:
    - KAMAL_REGISTRY_PASSWORD
