# yaml-language-server: $schema=https://raw.githubusercontent.com/kjellberg/mrsk/validate-with-json-schema/lib/mrsk/configuration/schema.yaml
service: web
image: fogtype/caddy
servers:
  - ubuntu@gamma.fogtype.com
registry:
  username: fogtype
  password:
    - KAMAL_REGISTRY_PASSWORD
logging:
  driver: journald
healthcheck:
  cmd: /bin/true
