name: ssh-backup
services:
  openssh-server:
    image: linuxserver/openssh-server
    ports:
      - "2222:2222"
    environment:
      PUID: "1000"
      PGID: "1000"
      PASSWORD_ACCESS: "true"
      USER_NAME: backup
      USER_PASSWORD: ${BACKUP_PASSWORD:?} # BACKUP_PASSWORD=$(openssl rand -base64 8 | tee /dev/stderr) docker compose up
    volumes:
      - ./backup:/config/backup
