services:
  webui:
    image: ghcr.io/seyys/ytdlp-webui:master
    restart: unless-stopped
    ports:
      - 5000:5000
    depends_on:
      - redis
  worker:
    image: ghcr.io/seyys/ytdlp-webui:master
    restart: unless-stopped
    command: ["celery", "-A", "make_celery", "worker", "--loglevel", "INFO"]
    user: 1000:1000
    environment:
      FILENAME_TEMPLATE: "%(uploader|Unknown)s,%(album|[Unknown Album])s,%(title)s [%(id)s]"
    volumes:
      - ./downloads:/app/downloads
      - ./config:/app/config
    depends_on:
      - redis
  redis:
    image: redis:alpine
    restart: unless-stopped
