[package]
name = "playwright-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
playwright = "0.0.20"
tokio = { version = "1.39.3", features = ["full"] }

[[bin]]
name = "playwright-rust"
path = "main.rs"
