name: coveralls
on: workflow_dispatch
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: coverallsapp/github-action@master
        with: { github-token: "${{ secrets.github_token }}" }
