name: release-it
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Increment "major", "minor", "patch", or "pre*" version; or specify version'
        default: patch
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          registry-url: https://registry.npmjs.org/
      - name: Release
        working-directory: release-it
        run: |
          npm i
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name "${GITHUB_ACTOR}"
          GITHUB_TOKEN="${{ github.token }}" npx release-it --ci -- "${{ github.event.inputs.version }}"
