name: update-latest-release
on:
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo ok > hello.txt
      # - uses: actions/github-script@v6
      #   with:
      #     script: |
      #       const { data: release } = await github.rest.repos.getLatestRelease(context.repo);

      #       const name = "hello.txt";
      #       const data = await require("node:fs").promises.readFile(name);

      #       await github.rest.repos.uploadReleaseAsset({
      #         ...context.repo,
      #         release_id: release.id,
      #         name,
      #         data,
      #       });
      - run: |
          latest=$(gh release view --json tagName --jq .tagName)
          gh release delete-asset "${latest}" hello.txt || :
          gh release upload "${latest}" hello.txt
        env:
          GH_TOKEN: ${{ github.token }}
